[project]
name = "xugrid"
version = "0.8.0"
description = "Xarray extension for unstructured grids"
authors = ["Huite Bootsma <huite.bootsma@deltares.nl>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
license = "MIT"
license-file = "LICENSE"
homepage = "https://deltares.github.io/xugrid/"
documentation = "https://deltares.github.io/xugrid/"
repository = "https://github.com/Deltares/xugrid"

[tasks]
install = "python -m pip install --no-deps --editable ."
install-pre-commit = "pre-commit install"
pre-commit = "pre-commit run --all-files"
test = { depends_on = ["install"], cmd = "NUMBA_DISABLE_JIT=1 pytest --cov=xugrid --cov-report xml --cov-report term"}
docs = { depends_on = ["install"], cmd = "NUMBA_DISABLE_JIT=1 sphinx-build docs docs/_build"}
all = { depends_on = ["pre-commit", "test", "docs"]}

[dependencies]
dask = "*"
geopandas = "*"
mapbox_earcut = "*"
matplotlib-base = "*"
netcdf4 = "*"
numba_celltree = "*"
pip = "*"
pooch = "*"
pre-commit = "*"
pydata-sphinx-theme = "*"
pymetis = "*"
pyproj = "*"
pytest = "*"
pytest-cov = "*"
python = ">=3.9"
ruff = "*"
shapely = ">=2.0"
scipy = "*"
sphinx = "*"
sphinx-gallery = "*"
xarray = "*"
zarr = "*"
ipykernel = "6.26.0.*"  # So we can run examples
