name: test-py3.9

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.3.0
      - name: install py3.9
        run: pixi add python=3.9
      - name: Run Tests 3.9
        run: pixi run test